[workspace]
members = [
    "core/*",
    "bindings/*"
]

[workspace.dependencies]
ahash = "0.8.3"
async-trait = "0.1.66"
bincode = "2.0.0-rc.2"
bumpalo = "3.12.0"
chrono = "0.4.23"
criterion = "0.4.0"
fastrand = "1.9.0"
humantime = "2.1.0"
once_cell = "1.17.1"
phf = "0.11.1"
serde_json = "1.0.91"
hashbrown = "0.13.2"
rust_decimal = "1.28.0"
rust_decimal_macros = "1.28.0"

anyhow = "1.0.69"
thiserror = "1.0.38"
